### ISSUE TITLE
on ../../terraform-units/modules/sap_deployer/key_vault.tf line 120, in resource "azurerm_key_vault_access_policy" "kv_user_pre_deployer":

### ISSUE THREAD

**Issue by satish-gurjar** [Azure/sap-automation#155] opened 2022-05-06 15:09 UTC
When I use SAP automation framework tutorial for deployment Hands-on lab  ..After setting  environment variable and other pre-requisites steps , when I execute the 

"${DEPLOYMENT_REPO_PATH}/deploy/scripts/prepare_region.sh  " to deploy the deployer -- I am running into key vault issue 

------------
============== 
########################################################################################
#                                                                                       #
#                              during the plan phase                              #
#                                                                                       #
#########################################################################################

╷
│ Error: Error in function call
│ 
│   on ../../terraform-units/modules/sap_deployer/key_vault.tf line 120, in resource "azurerm_key_vault_access_policy" "kv_user_pre_deployer":
│  120:   object_id = coalesce(
│  121:     data.azurerm_client_config.deployer.object_id,
│  122:     data.azurerm_client_config.deployer.client_id,
│  123:     var.arm_client_id
│  124:   )
│     ├────────────────
│     │ data.azurerm_client_config.deployer.client_id is ""
│     │ data.azurerm_client_config.deployer.object_id is ""
│     │ var.arm_client_id is ""
│ 
│ Call to function "coalesce" failed: no non-null, non-empty-string
│ arguments.
╵
satish@Azure:~/Azure_SAP_Automated_Deployment/WORKSPACES$
--------------------------------------- 

Appreciate any help on this ..

Satish Gurjar

**Comment by jkirkmannz** [comment] 2022-05-06 18:35
Hi Salish,
Grant the userID you are using rights to create/view/update secrets in the deployed vault you created.

Regards,
John

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: satish-gurjar ***@***.***>
Sent: Saturday, May 7, 2022 3:09:20 AM
To: Azure/sap-automation ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Azure/sap-automation] on ../../terraform-units/modules/sap_deployer/key_vault.tf line 120, in resource "azurerm_key_vault_access_policy" "kv_user_pre_deployer": (Issue #155)


When I use SAP automation framework tutorial for deployment Hands-on lab ..After setting environment variable and other pre-requisites steps , when I execute the

"${DEPLOYMENT_REPO_PATH}/deploy/scripts/prepare_region.sh " to deploy the deployer -- I am running into key vault issue

________________________________

==============
########################################################################################

during the plan phase

#########################################################################################

╷
│ Error: Error in function call
│
│ on ../../terraform-units/modules/sap_deployer/key_vault.tf line 120, in resource "azurerm_key_vault_access_policy" "kv_user_pre_deployer":
│ 120: object_id = coalesce(
│ 121: data.azurerm_client_config.deployer.object_id,
│ 122: data.azurerm_client_config.deployer.client_id,
│ 123: var.arm_client_id
│ 124: )
│ ├────────────────
│ │ data.azurerm_client_config.deployer.client_id is ""
│ │ data.azurerm_client_config.deployer.object_id is ""
│ │ var.arm_client_id is ""
│
│ Call to function "coalesce" failed: no non-null, non-empty-string
│ arguments.
╵
***@***.***:~/Azure_SAP_Automated_Deployment/WORKSPACES$

Appreciate any help on this ..

Satish Gurjar

—
Reply to this email directly, view it on GitHub<https://clicktime.symantec.com/3BaYi6SojAjxjL9ufNmzm8b7VN?u=https%3A%2F%2Fgithub.com%2FAzure%2Fsap-automation%2Fissues%2F155>, or unsubscribe<https://clicktime.symantec.com/3GfAnDydEFh1bMq3ZMZUqY77VN?u=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAJHBSTTI64EBU7YSUIRI4ITVIUY2BANCNFSM5VIOK67A>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

DXC Technology NZ Limited (Company number 1441241).
DXC Technology Company -- This message is transmitted to you by or on behalf of DXC Technology Company or one of its affiliates. It is intended exclusively for the addressee. The substance of this message, along with any attachments, may contain proprietary, confidential or privileged information or information that is otherwise legally exempt from disclosure. Any unauthorized review, use, disclosure or distribution is prohibited. If you are not the intended recipient of this message, you are not authorized to read, print, retain, copy or disseminate any part of this message. If you have received this message in error, please destroy and delete all copies and notify the sender by return e-mail. Regardless of content, this e-mail shall not operate to bind DXC Technology Company or any of its affiliates to any order or other contract unless pursuant to explicit written agreement or government initiative expressly permitting the use of e-mail for such purpose.

**Comment by KimForss** [comment] 2022-06-15 11:31
Hi @satish-gurjar,  can you reproduce this with the latest release?

//Kimmo

**Comment by barisberkbulut** [comment] 2022-07-23 12:31
@KimForss I'm having the exact error with the new version. 
Since it is the beginning of the deployment, there isn't any Key Vault created at that point.

**Comment by KimForss** [comment] 2022-07-25 12:19
Hi @satish-gurjar 

Can you before running prepare-region, run az logoff and then az login (either using the service principal or your account)

I assume that what is happening is that Terraform is unable to pick up the object ID for the current session . I have seen this happen when using Azure Cloudshell using the default credentials

**Comment by barisberkbulut** [comment] 2022-08-02 20:04
Hi @KimForss 

Az logoff - login tried with my account and still outputs the same error.

**Comment by gdiren** [comment] 2022-08-09 10:51
Hi @KimForss

I am also stuck with the same error message "Call to function "coalesce" failed: no non-null, non-empty-string
│ arguments."

**Comment by enterprise-1701-d** [comment] 2022-08-09 12:19
Hi @KimForss, I just run everything from scratch (not adjusting anything) in Azure-Cli and have the same issue:

azureuser@Azure:~/Azure_SAP_Automated_Deployment/WORKSPACES$ ${DEPLOYMENT_REPO_PATH}/deploy/scripts/prepare_region.sh --deployer_parameter_file DEPLOYER/${env_code}-${region_code}-DEP00-INFRASTRUCTURE/${env_code}-${region_code}-DEP00-INFRASTRUCTURE.tfvars  --library_parameter_file LIBRARY/${env_code}-${region_code}-SAP_LIBRARY/${env_code}-${region_code}-SAP_LIBRARY.tfvars --subscription "${subscriptionId}" --spn_id "${spn_id}" --spn_secret "${spn_secret}" --tenant_id "${tenant_id}" --auto-approve
ADO flag 
Validating DEPLOYER/MGMT-WEEU-DEP00-INFRASTRUCTURE/MGMT-WEEU-DEP00-INFRASTRUCTURE.tfvars
Region code for deployment:  WEEU
/home/azureuser/Azure_SAP_Automated_Deployment/sap-automation/deploy/scripts/prepare_region.sh: line 136: [: =: unary operator expected
#########################################################################################
#                                                                                       #
#                    Starting the control plane deployment                              #
#                                                                                       #
#########################################################################################


#########################################################################################
#                                                                                       #
#        Changing the subscription to: 13f22992-de24-4eae-8547-aa77252834da             #
#                                                                                       #
#########################################################################################

        [set_executing_user_environment_variables]: Identifying the executing user and client
                [set_azure_cloud_environment]: Identifying the executing cloud environment
                [set_azure_cloud_environment]: Azure cloud environment: public
                [set_executing_user_environment_variables]: User type: user
        [set_executing_user_environment_variables]: Identified login type as 'user'
                [unset_executing_user_environment_variables]: unsetting ARM_* environment variables
        [set_executing_user_environment_variables]: logged in user id: e5ce23f0-33cd-45c1-a6a3-bd68d80e5976 (jakob.sauer_sva.de#EXT#@jakobsauersva.onmicrosoft.com)
        [set_executing_user_environment_variables]: Initializing state with user: jakob.sauer_sva.de#EXT#@jakobsauersva.onmicrosoft.com

#########################################################################################
#                                                                                       #
#                           Bootstrapping the deployer                                  #
#                                                                                       #
#########################################################################################

--parameterfile MGMT-WEEU-DEP00-INFRASTRUCTURE.tfvars --auto-approve
Parameter file: MGMT-WEEU-DEP00-INFRASTRUCTURE.tfvars
Validating MGMT-WEEU-DEP00-INFRASTRUCTURE.tfvars
#########################################################################################
#                                                                                       #
#                                   New deployment                                      #
#                                                                                       #
#########################################################################################
Initializing modules...
- sap_deployer in ../../terraform-units/modules/sap_deployer
- sap_namegenerator in ../../terraform-units/modules/sap_namegenerator

Initializing the backend...

Successfully configured the backend "local"! Terraform will automatically
use this backend unless the backend configuration changes.

Initializing provider plugins...
- Finding latest version of hashicorp/external...
- Finding latest version of hashicorp/local...
- Finding latest version of hashicorp/random...
- Finding latest version of hashicorp/null...
- Finding latest version of hashicorp/tls...
- Finding hashicorp/azurerm versions matching "~> 3.0"...
- Using hashicorp/external v2.2.2 from the shared cache directory
- Using hashicorp/local v2.2.3 from the shared cache directory
- Using hashicorp/random v3.3.2 from the shared cache directory
- Using hashicorp/null v3.1.1 from the shared cache directory
- Using hashicorp/tls v4.0.1 from the shared cache directory
- Using hashicorp/azurerm v3.17.0 from the shared cache directory

Terraform has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.

╷
│ Warning: Incomplete lock file information for providers
│ 
│ Due to your customized provider installation methods, Terraform was forced to calculate lock file checksums locally for the following providers:
│   - hashicorp/azurerm
│   - hashicorp/external
│   - hashicorp/local
│   - hashicorp/null
│   - hashicorp/random
│   - hashicorp/tls
│ 
│ The current .terraform.lock.hcl file only includes checksums for linux_amd64, so Terraform running on another platform will fail to install these providers.
│ 
│ To calculate additional checksums for another platform, run:
│   terraform providers lock -platform=linux_amd64
│ (where linux_amd64 is the platform to generate)
╵

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.

#########################################################################################
#                                                                                       #
#                             Running Terraform plan                                    #
#                                                                                       #
#########################################################################################


#########################################################################################
#                                                                                       #
#                              Errors during the plan phase                               #
#                                                                                       #
#########################################################################################

data.azurerm_client_config.current: Reading...
module.sap_deployer.data.azurerm_client_config.current: Reading...
module.sap_deployer.data.azurerm_client_config.deployer: Reading...
module.sap_deployer.data.azurerm_subscription.primary: Reading...
module.sap_deployer.data.azurerm_client_config.deployer: Read complete after 0s [id=2022-08-09 12:10:12.924960108 +0000 UTC]
data.azurerm_client_config.current: Read complete after 0s [id=2022-08-09 12:10:12.9243992 +0000 UTC]
module.sap_deployer.data.azurerm_client_config.current: Read complete after 0s [id=2022-08-09 12:10:12.927077336 +0000 UTC]
module.sap_deployer.data.azurerm_subscription.primary: Read complete after 0s [id=/subscriptions/13f22992-de24-4eae-8547-aa77252834da]
╷
│ Error: Error in function call
│ 
│   on ../../terraform-units/modules/sap_deployer/key_vault.tf line 73, in resource "azurerm_key_vault_access_policy" "kv_user_pre_deployer":
│   73:   object_id = coalesce(
│   74:     data.azurerm_client_config.deployer.object_id,
│   75:     data.azurerm_client_config.deployer.client_id,
│   76:     var.arm_client_id
│   77:   )
│     ├────────────────
│     │ data.azurerm_client_config.deployer.client_id is ""
│     │ data.azurerm_client_config.deployer.object_id is ""
│     │ var.arm_client_id is ""
│ 
│ Call to function "coalesce" failed: no non-null, non-empty-string
│ arguments.

**Comment by PankajMeshramCSA** [comment] 2022-12-19 14:45
@satish-gurjar  - Please check the latest guide available here - https://learn.microsoft.com/en-us/azure/virtual-machines/workloads/sap/automation-devops-tutorial

**Comment by PankajMeshramCSA** [comment] 2022-12-19 15:04
@satish-gurjar has confirmed the closure -   "thank you, Pankaj  for reaching out to me ...Please close it . I had to remove the infrastructure for scarcity of resource .. I will try it out again with latest guide and reach out to team if any issue."

**Closed by PankajMeshramCSA** 2022-12-19 15:04 UTC
Labels: bug
